// Copyright (c) 2026 Alexander Hefner
// 
// Licensed under the MIT License - see LICENSE.txt file for details

#include <bur/plctypes.h>

#ifdef __cplusplus
	extern "C"
	{
#endif

#include <stdint.h>
#include <string.h>
#include <AsTime.h>
#include <standard.h>
#include <AsETH.h>
#include "UUIDgen.h"

#ifdef __cplusplus
	};
#endif

/* --- AI generated code ---- */
// ************ each function / code / comment inside this block was generated by Google AI Assistant and maybe / partly adapted by human *************

// generated by Google AI Assistent 12.08.2026
// global variables for Xoshiro256**Generator
static uint64_t s_state[4];
static uint64_t rotl(const uint64_t x, int k) {
	return (x << k) | (x >> (64 - k));
}

// generated by Google AI Assistent 12.08.2026
// generate next random number
uint64_t next_random(void) {
	const uint64_t result = rotl(s_state[1] * 5, 7) * 9;
	const uint64_t t = s_state[1] << 17;

	s_state[2] ^= s_state[0];
	s_state[3] ^= s_state[1];
	s_state[1] ^= s_state[2];
	s_state[0] ^= s_state[3];

	s_state[2] ^= t;
	s_state[3] = rotl(s_state[3], 45);

	return result;
}

// generated by Google AI Assistent 12.08.2026
// hepler function: mix entropy bits into generator start vector (Fisher-Yates / hash-like)
// call this multiple times with random values for initialization of the generator
void inject_entropy(uint32_t raw_value) {
	static int index = 0;
	// use entropy bits to mix the state with xor
	s_state[index % 4] ^= ((uint64_t)raw_value << (index % 2 ? 32 : 0)) ^ 0x9E3779B97F4A7C15ULL;
	index++;
}

// generated by Google AI Assistent 12.08.2026
// generate the UUIDv4 token data
void generate_embedded_uuid(char *out_uuid) {
	uint64_t r1 = next_random();
	uint64_t r2 = next_random();

	uint8_t bytes[16];
	memcpy(&bytes[0], &r1, 8);
	memcpy(&bytes[8], &r2, 8);

	// force UUIDv4 spec
	bytes[6] = (bytes[6] & 0x0F) | 0x40; // version 4
	bytes[8] = (bytes[8] & 0x3F) | 0x80; // variant 1

	memcpy(out_uuid, bytes, sizeof(bytes));
}

// generated by Google AI Assistent 13.08.2026
#define UUID_BLOCKSIZE 16
int32_t UsintToHex(const uint8_t* pIn, uint8_t* pHex)
{
	// lookup-table for hex chars
	static const char hexChars[] = "0123456789abcdef";
	uint16_t i = 0;
	
	for (i = 0; i < UUID_BLOCKSIZE; i++)
	{
		uint8_t byte = pIn[i];
		// high nibble
		pHex[2 * i]     = hexChars[byte >> 4];
		// low nibble
		pHex[2 * i + 1] = hexChars[byte & 0x0F];
	}
    
	// string termination
	pHex[2 * UUID_BLOCKSIZE] = '\0'; 
	return 0;
}

// ************ each function / code / comment inside this block was generated by Google AI Assistant and maybe / partly slightly adapted by human *************
/* --- END OF AI generated code ---- */

// add uuid defined separators -> 36 chars + \0 is result!
void HexStrToUUID(const uint8_t* pHex, uint8_t* pUUID)
{
	uint32_t offsetDest = 0;
	uint32_t offsetSrc = 0;
	uint8_t i = 0;
	
	memcpy(pUUID + offsetDest, pHex + offsetSrc, 8);
	offsetDest += 8;
	offsetSrc += 8;
	memset(pUUID + offsetDest, '-', 1);
	offsetDest += 1;
	for (i = 0; i < 3; i++)
	{
		memcpy(pUUID + offsetDest, pHex + offsetSrc, 4);
		offsetDest += 4;
		offsetSrc += 4;
		memset(pUUID + offsetDest, '-', 1);
		offsetDest += 1;
	}
	memcpy(pUUID + offsetDest, pHex + offsetSrc, 12);
	offsetDest += 12;
	memset(pUUID + offsetDest, 0, 1);
}

// read the device date and time 
uint32_t GetDTSecs(void)
{
	DTGetTime_typ dt;
	dt.enable = 1;
	DTGetTime(&dt);
	if (dt.status == 0)
		return dt.DT1;
	else
		return 0;
}

// generate seed based on entropy data (fallback: based on rtc) & predefined prime numbers
uint32_t generate_seed(uint32_t number, uint32_t mix, uint32_t salt)
{
	return (number * mix) + salt;
}

// c global vars
//TON_typ ton_0 = {0};
//ethSTATISTICS_typ stat = {0};
//EthStat_typ ethstat_0 = {0};
//uint32_t start_val = 0;
//uint8_t run_count = 0;
//uint8_t step = 0;
//uint16_t internal_status = 0;
//uint16_t internal_error = 0;

#define RUN_COUNT 10
uint32_t primes1[10] = {99929,96661,90007,85453,80051,75521,60083,51199,40013,22277};
uint32_t primes2[10] = {10007,12347,54323,88861,99991,15427,33349,76897,71119,95561};

void UUIDGenerator(UUIDGenerator_typ* inst)
{

	uint8_t array[16] = {0};
	uint8_t uuid[33] = {0};
	uint8_t uuid_hyphened[37] = {0};
	
	if (inst->internal.enable_last == 0 && inst->enable == 1)
	{
		// p edge
		inst->internal.internal_status = 65535;
		inst->internal.internal_error = 0;
		inst->internal.run_count = 0;
		inst->internal.step = 1;
		inst->phase = uuidgenPHASE_INITIALIZING;
	}
	inst->internal.enable_last = inst->enable;
	
	if (inst->enable == 0)
	{
		inst->phase = uuidgenPHASE_STOPPED;	
	}
	
	switch (inst->internal.step)
	{
		case 0:
			
			if (inst->internal.getnext_last == 0 && inst->getNextUUID == 1)
			{
				// p edge
				if (inst->enable == 1 && inst->phase == uuidgenPHASE_READY)
				{
					inst->internal.step = 3;
				}
			}
			inst->internal.getnext_last = inst->getNextUUID;
			break;
		
		// wait 0.1 second, then go on with next step
		case 1:
			inst->internal.ton_0.PT = 100;
			inst->internal.ton_0.IN = 1;
			TON(&inst->internal.ton_0);
			if (inst->internal.ton_0.Q == 1)
			{
				inst->internal.step++;
				inst->internal.ton_0.IN = 0;
				TON(&inst->internal.ton_0);
			}
			break;

		// get eth stats & rtc time, build some more, real external random values out of those values
		case 2:
			inst->internal.ethstat_0.enable = 1;
			inst->internal.ethstat_0.pDevice = (UDINT)&inst->ethIfName;
			inst->internal.ethstat_0.pStat = (UDINT)&inst->internal.stat;
			EthStat(&inst->internal.ethstat_0);
			if (inst->internal.ethstat_0.status != 65535)
			{
				if (inst->internal.ethstat_0.status == 0 && inst->internal.stat.bytesrecv > 0)
				{
					// use bytes received as external entropy value
					inst->internal.start_val = generate_seed(inst->internal.stat.bytesrecv, primes1[inst->internal.run_count], primes2[inst->internal.run_count]);
				}
				else
				{
					// JUST AS FALLBACK: use clock instead of network bytes, but be aware that the clock value does not change within the 10 rounds 
					inst->internal.start_val = generate_seed(GetDTSecs(), primes1[inst->internal.run_count], primes2[inst->internal.run_count]);
					inst->internal.internal_error = 1; // just as a "marker" to know that reading eth stat failed for whatever reason
				}
				// use that value as initialisation vector for the generator
				inject_entropy(inst->internal.start_val);
				// repeat initialisation 10 times, once a second to get different random eth stat data
				if (inst->internal.run_count >= RUN_COUNT - 1)
				{
					inst->internal.step++;
				}
				else
				{
					inst->internal.step--;
					inst->internal.run_count++;
				}
			}
			
			break;	

		// uuid generation
		// Important: after first initialisation (steps 1 + 2), it's not needed to init again to get new uuids -> just execute this step 3 again to get a new uuid!!
		case 3:
			inst->phase = uuidgenPHASE_READY; // preparation finished!
			inst->internal.internal_status = 0;
			
			generate_embedded_uuid((char*)&array); // generate a uuid
			UsintToHex(array, (uint8_t*)uuid); // get uuid as hex string
			HexStrToUUID(uuid, uuid_hyphened);
			// output the "flat" result
			strcpy(inst->UUID, (char*)uuid);
			// A UUID version 4, variant 1 follows the standard 8-4-4-4-12 hex format (xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx),
			// where the 13th character is always 4 (denoting version 4) and the 17th character starts with 8, 9, a, or b (denoting variant 1).
			strcpy(inst->UUIDhyphened, (char*)uuid_hyphened);
			
			// done
			inst->internal.step = 0;
			break;
		
		default:
			inst->internal.step = 0;
			break;
	}

}
